[project]
name = "api-dadoconcreto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-ninja>=1.3.0",
]

[tool.uv]
dev-dependencies = [
    "aider-chat>=0.62.0",
    "pytest>=8.3.3",
]
